AWSTemplateFormatVersion: 2010-09-09
Description: "Guidance to create VPC endpoints for federated demo data sources"
Parameters:
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Project's SecurityGroupId

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId associated with the SageMaker Domain

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Selected Subnets. us-east-1 supports only 1b, 1c, 1d AZs for Redshift Serverless Endpoint.

  RouteTableId:
    Type: String
    Description: RouteTableId. Used to enabled S3 Gateway endpoint.

Resources:        
  VPCEndpointSecretsManager:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.secretsmanager"
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId          

  VPCEndpointSTS:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.sts"
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId

  VPCEndpointGlue:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.glue"
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId 

  VPCEndpointRDSData:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.rds-data"
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId

  VPCEndpointRedshiftData:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.redshift-data"
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId 

  VPCEndpointRedshiftServerless:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.redshift-serverless"
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId

  EndpointS3:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      RouteTableIds:
        - !Ref RouteTableId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      VpcEndpointType: "Gateway"
      VpcId: !Ref VpcId 

