AWSTemplateFormatVersion: 2010-09-09
Description: "Guidance to create VPC endpoints for federated demo data sources"
Parameters:
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Project's SecurityGroupId

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId associated with the SageMaker Domain

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: PublicSubnet1

Resources:        
  VPCEndpointSecretsManager:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.secretsmanager"
      PolicyDocument: |
        {
          "Statement": [
            {
              "Action": "*", 
              "Effect": "Allow", 
              "Principal": "*", 
              "Resource": "*"
            }
          ]
        }
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId          

  VPCEndpointSTS:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.sts"
      PolicyDocument: |
        {
          "Statement": [
            {
              "Action": "*", 
              "Effect": "Allow", 
              "Principal": "*", 
              "Resource": "*"
            }
          ]
        }
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId

  VPCEndpointGlue:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.glue"
      PolicyDocument: |
        {
          "Statement": [
            {
              "Action": "*", 
              "Effect": "Allow", 
              "Principal": "*", 
              "Resource": "*"
            }
          ]
        }
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId 

  VPCEndpointRDSData:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.rds-data"
      PolicyDocument: |
        {
          "Statement": [
            {
              "Action": "*", 
              "Effect": "Allow", 
              "Principal": "*", 
              "Resource": "*"
            }
          ]
        }
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId 

  VPCEndpointRedshiftData:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.redshift-data"
      PolicyDocument: |
        {
          "Statement": [
            {
              "Action": "*", 
              "Effect": "Allow", 
              "Principal": "*", 
              "Resource": "*"
            }
          ]
        }
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId 

  VPCEndpointRedshiftServerless:
    Type: "AWS::EC2::VPCEndpoint"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Delete"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.redshift-serverless"
      PolicyDocument: |
        {
          "Statement": [
            {
              "Action": "*", 
              "Effect": "Allow", 
              "Principal": "*", 
              "Resource": "*"
            }
          ]
        }
      SubnetIds: !Ref SubnetIds
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId